### ISSUE TITLE
Import error?

### ISSUE THREAD

**Issue by vysec** [lgandx/Responder-Windows#3]
Error

Sometimes the following and sometimes

"import exit failed"

```
C:\Users\xxx\Desktop\Responder-Windows\binaries\Responder>Responder.exe -A -i 192.168.1.197
                                         __
  .----.-----.-----.-----.-----.-----.--|  |.-----.----.
  |   _|  -__|__ --|  _  |  _  |     |  _  ||  -__|   _|
  |__| |_____|_____|   __|_____|__|__|_____||_____|__|
                   |__|

           NBT-NS, LLMNR & MDNS Windows Responder 2.3.3.0

  Author: Laurent Gaffie (laurent.gaffie@gmail.com)
  To kill this script hit CRTL-C

/!\ Warning: files/AccessDenied.html: file not found
/!\ Warning: files/BindShell.exe: file not found

[+] Poisoners:
    LLMNR                      [ON]
    NBT-NS                     [ON]
    DNS/MDNS                   [ON]

[+] Servers:
    HTTP server                [ON]
    HTTPS server               [ON]
    WPAD proxy                 [OFF]
    Auth proxy                 [OFF]
    SMB server                 [ON]
    Kerberos server            [ON]
    SQL server                 [ON]
    FTP server                 [ON]
    IMAP server                [ON]
    POP3 server                [ON]
    SMTP server                [ON]
    DNS server                 [ON]
    LDAP server                [ON]

[+] HTTP Options:
    Always serving EXE         [OFF]
    Serving EXE                [OFF]
    Serving HTML               [OFF]
    Upstream Proxy             [OFF]

[+] Poisoning Options:
    Analyze Mode               [ON]
    Force WPAD auth            [OFF]
    Force Basic Auth           [OFF]
    Force LM downgrade         [OFF]
    Fingerprint hosts          [OFF]

[+] Generic Options:
    Responder NIC              [ALL]
    Responder IP               [0.0.0.0]
    Challenge set              [1122334455667788]
    Don't Respond To Names     ['ISATAP']



[i] Responder is in analyze mode. No NBT-NS, LLMNR, MDNS requests will be poisoned.
Preparing Windows for Responder...
Disabling NetBIOS...
Executing (\\xxx\ROOT\CIMV2:Win32_NetworkAdapterConfiguration.Index=1)->SetTcpipNetbios()
Method execution successful.
Out Parameters:
instance of __PARAMETERS
{
        ReturnValue = 0;
};

Executing (\\xxx\ROOT\CIMV2:Win32_NetworkAdapterConfiguration.Index=2)->SetTcpipNetbios()
Method execution successful.
Out Parameters:
instance of __PARAMETERS
{
        ReturnValue = 0;
};

Executing (\\xxx\ROOT\CIMV2:Win32_NetworkAdapterConfiguration.Index=3)->SetTcpipNetbios()
Method execution successful.
Out Parameters:
instance of __PARAMETERS
{
        ReturnValue = 0;
};

Turning firewall Off...

IMPORTANT: Command executed successfully.
However, "netsh firewall" is deprecated;
use "netsh advfirewall firewall" instead.
For more information on using "netsh advfirewall firewall" commands
instead of "netsh firewall", see KB article 947709
at http://go.microsoft.com/fwlink/?linkid=121488 .

Ok.

Ready!
Traceback (most recent call last):
  File "Responder.py", line 296, in <module>
  File "Responder.py", line 206, in main
  File "C:\Python27\Lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
  File "poisoners\LLMNR.py", line 45, in <module>
  File "poisoners\LLMNR.py", line 32, in IsICMPRedirectPlausible
IOError: [Errno 2] No such file or directory: '/etc/resolv.conf'
Failed to execute script Responder
```

**Comment by lgandx** [comment]
Nice catch! Will drop a fix

**Comment by lgandx** [comment]
Fixed. 
Thanks for your report!
